replicaCount: 1

image:
    repository: zot.lan/kitti12911/grpc-sandbox
    tag: ""
    digest: ""
    pullPolicy: IfNotPresent

imagePullSecrets:
    - name: zot-registry

env: []

reloader:
    enabled: true

podSecurityContext: {}

securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
        drop:
            - ALL
    seccompProfile:
        type: RuntimeDefault

resources:
    requests:
        cpu: 50m
        memory: 64Mi
    limits:
        cpu: 250m
        memory: 256Mi

service:
    type: ClusterIP
    port: 50051

configSecret:
    create: true
    name: ""

probes:
    readiness:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 3
    liveness:
        enabled: true
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3

config:
    service:
        name: grpc-sandbox
        port: 50051
        shutdown_timeout: 10s

    logging:
        level: warn
        add_source: false
        include_trace_id: true

    tracing:
        enabled: true
        endpoint: alloy.lan:4317
        protocol: grpc
        insecure: false
        sample_ratio: 1.0

    profiling:
        enabled: true
        server_address: https://pyroscope-ingest.lan
        namespace: grpc-sandbox
        basic_auth_user: ""
        basic_auth_password: ""
        tenant_id: ""

    database:
        host: postgres.lan
        port: "5432"
        user: example_user
        password: example_password
        database: example
        run_migrations: true
        run_seeders: false
        pool:
            max_conns: 20
            min_conns: 5
            max_conn_life_time: 1h
            max_conn_idle_time: 6h
