name: Helm Lint

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/helm-lint.yml"
            - "Makefile"
            - "scripts/ci/helm-lint.sh"
            - "charts/**"
            - "!README.md"
    pull_request:
        paths:
            - ".github/workflows/helm-lint.yml"
            - "Makefile"
            - "scripts/ci/helm-lint.sh"
            - "charts/**"
            - "!README.md"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    helm-lint:
        name: Helm Lint
        runs-on: ubuntu-latest
        container:
            image: ${{ vars.TOOLCHAIN_REGISTRY }}/${{ vars.TOOLCHAIN_IMAGE_NAMESPACE }}/helm-toolchain@sha256:8cfadaaea735e97e5223d5f83ee40269f003f14709cc8b07bf907fc528fb475e
            credentials:
                username: ${{ secrets.TOOLCHAIN_REGISTRY_USERNAME }}
                password: ${{ secrets.TOOLCHAIN_REGISTRY_PASSWORD }}
        steps:
            # actions/checkout v6.0.2
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

            - name: Helm lint
              run: ./scripts/ci/helm-lint.sh
